ops:
  er_pair_scores:
    config:
      features_table: "er.pair_features"          # or an aggregated view/table
      model_path: "models/er_pair_clf.joblib"     # your saved sklearn Pipeline
      out_parquet: "data/er/pair_scores/score.parquet"
      batch_size: 10000000